add dyn cfg replace_out_of_range_with_max_range
BadgerTechnologies/velodyne pull request #3
Opened 2020-10-14 21:34 UTC by c-andy-martin

Add a new dynamic configure option to replace out-of-range data with
whatever the maximum range is set to. This is useful for implementing
clearing-on-invalid in a costmap context by setting the max range
beyond the max range used as the maximum obstacle range in a costmap.
The default is disabled.

2020-10-15 12:12 UTC, dandedrick requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/velodyne/3)* status: all files reviewed, 2 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[velodyne_pointcloud/src/lib/rawdata.cc, line 397 at r1](https://reviewable.io/reviews/badgertechnologies/velodyne/3#-MJg9ASnE_0ewafnonpJ:-MJg9ASo2-N02UpP_lSb:b-5guark) ([raw file](https://github.com/badgertechnologies/velodyne/blob/92c89dbaeb5fceb4fef3ae562a860f59be0167f7/velodyne_pointcloud/src/lib/rawdata.cc#L397)):*
> ```cpp
>             if (config_.replace_out_of_range_with_max_range)
>             {
> 	    ROS_WARN_STREAM_THROTTLE(60, "Replace out of range value (" << distance << ") with " << config_.max_range);
> ```

This tab needs to be expanded to spaces.
___
*[velodyne_pointcloud/src/lib/rawdata.cc, line 402 at r1](https://reviewable.io/reviews/badgertechnologies/velodyne/3#-MJg9o1p0YY0Rx9mneMD:-MJg9o1p0YY0Rx9mneME:b-cx6csj) ([raw file](https://github.com/badgertechnologies/velodyne/blob/394a9de841e3d600fd086f9f2f24fa2e282cb6ad/velodyne_pointcloud/src/lib/rawdata.cc#L402)):*
> ```cpp
> 
>             // convert polar coordinates to Euclidean XYZ
>             float distance = tmp.uint * calibration_.distance_resolution_m;
> ```

This change is unrelated and should be split out to a different commit and when pushing upstream possibly a different PR as it doesn't seem to correlate to the other changes.


<!-- Sent from Reviewable.io -->

2020-10-20 15:18 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/velodyne/3)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @dandedrick and @howardcochran)

___
*[velodyne_pointcloud/src/lib/rawdata.cc, line 397 at r1](https://reviewable.io/reviews/badgertechnologies/velodyne/3#-MJg9ASnE_0ewafnonpJ:-MK5_QmmDvMH2hrz69WW:b-886gsx) ([raw file](https://github.com/badgertechnologies/velodyne/blob/92c89dbaeb5fceb4fef3ae562a860f59be0167f7/velodyne_pointcloud/src/lib/rawdata.cc#L397)):*
<details><summary><i>Previously, dandedrick (Dan Dedrick) wrote…</i></summary><blockquote>

This tab needs to be expanded to spaces.
</blockquote></details>

Fixed
___
*[velodyne_pointcloud/src/lib/rawdata.cc, line 402 at r1](https://reviewable.io/reviews/badgertechnologies/velodyne/3#-MJg9o1p0YY0Rx9mneMD:-MK5_Sfe1RDOS4K35qkd:b-yp3rmq) ([raw file](https://github.com/badgertechnologies/velodyne/blob/394a9de841e3d600fd086f9f2f24fa2e282cb6ad/velodyne_pointcloud/src/lib/rawdata.cc#L402)):*
<details><summary><i>Previously, dandedrick (Dan Dedrick) wrote…</i></summary><blockquote>

This change is unrelated and should be split out to a different commit and when pushing upstream possibly a different PR as it doesn't seem to correlate to the other changes.
</blockquote></details>

This change is necessary to make the replace out of range work, but I agree it belongs in a pre-commit. I have moved it into its own commit, but will leave it with this PR as it is a required preliminary commit.


<!-- Sent from Reviewable.io -->

2020-10-20 15:18 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/velodyne/3)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @dandedrick and @howardcochran)

___
*[velodyne_pointcloud/src/lib/rawdata.cc, line 397 at r1](https://reviewable.io/reviews/badgertechnologies/velodyne/3#-MJg9ASnE_0ewafnonpJ:-MK5_gD0EK-w7iFhjhy6:b-896fix) ([raw file](https://github.com/badgertechnologies/velodyne/blob/92c89dbaeb5fceb4fef3ae562a860f59be0167f7/velodyne_pointcloud/src/lib/rawdata.cc#L397)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

Done.
___
*[velodyne_pointcloud/src/lib/rawdata.cc, line 402 at r1](https://reviewable.io/reviews/badgertechnologies/velodyne/3#-MJg9o1p0YY0Rx9mneMD:-MK5_f5j4NhIIWOAtcrp:b-896fix) ([raw file](https://github.com/badgertechnologies/velodyne/blob/394a9de841e3d600fd086f9f2f24fa2e282cb6ad/velodyne_pointcloud/src/lib/rawdata.cc#L402)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This change is necessary to make the replace out of range work, but I agree it belongs in a pre-commit. I have moved it into its own commit, but will leave it with this PR as it is a required preliminary commit.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-20 15:20 UTC, dandedrick reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/velodyne/3)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @dandedrick and @howardcochran)

___
*[velodyne_pointcloud/src/lib/rawdata.cc, line 402 at r1](https://reviewable.io/reviews/badgertechnologies/velodyne/3#-MJg9o1p0YY0Rx9mneMD:-MK5a3wUEgfy36Cn0304:bjlqsl7) ([raw file](https://github.com/badgertechnologies/velodyne/blob/394a9de841e3d600fd086f9f2f24fa2e282cb6ad/velodyne_pointcloud/src/lib/rawdata.cc#L402)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah yeah that makes sense.


<!-- Sent from Reviewable.io -->

2020-10-20 15:21 UTC, dandedrick approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/velodyne/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @howardcochran)



<!-- Sent from Reviewable.io -->

2020-10-20 15:27 UTC, merged